### PR TITLE
Fix deprecated usage of PropType via main React package

### LINKED ISSUE #3: Accessing PropTypes via the main React package is deprecated. Use the prop-types package instead.

### PR DESCRIPTION
**Pull request by kytwb**
Already bumped the package version with `npm version patch`.
Fixes #3.

### CODE REVIEW

**Comment by willianjusten** [comment]
Oh man thanks for that, I'm kind offline from my projects now...

**Comment by kytwb** [comment]
@willianjusten could you remember to do a quick `npm publish` please? :smile: Thanks!

**Comment by willianjusten** [comment]
Sorry for that, it's now published under `1.3.0` version.

**Comment by kytwb** [comment]
@willianjusten sweet! :+1:

**Pull request merged**
