### PR TITLE
Converted component to a controlled version

### PR DESCRIPTION
**Pull request by StanleySathler**
This PR convert the component's code to a controlled version, according to the request on #6. However it is still being discussed.

### CODE REVIEW

**Comment by willianjusten** [comment]
I didn't tested properly yet, but it would be nice to add tests to check the states and see if it works normally.

**Comment by StanleySathler** [comment]
You're definitely right. I'll be providing them soon.

**Comment by StanleySathler** [comment]
@willianjusten I added a few specs in order to test checkbox's `checked` prop. Do you think is there any other way to make it even better?

**Comment by StanleySathler** [comment]
@willianjusten I've updated the missing unit tests. Also, an important note: I changed the old Git history for this Pull Request, so, if you have pulled it, just remove the local branch and pull it again. The Git history became really ugly while applying some updates.

**Comment by willianjusten** [comment]
I'll take a look tomorrow morning, please don't let me forget this.

**Comment by StanleySathler** [comment]
@willianjusten just reminding you again 😋

**Comment by willianjusten** [comment]
Just tested here, everything works, the code looks fine as well. 
I'm not working with this component anymore, but I feel that this will be useful to more people =)

**Comment by willianjusten** [comment]
Release on [2.0.1](https://www.npmjs.com/package/lyef-switch-button)

**Pull request merged**
